update cfg

diff --git a/.config/polybar/checkupdate b/.config/polybar/checkupdate
--- a/.config/polybar/checkupdate
+++ b/.config/polybar/checkupdate
@@ -1,45 +1,48 @@
 #!/bin/bash
 
-if ! type -P fakeroot >/dev/null; then
-	error 'Cannot find the fakeroot binary'
-fi
+CHECKUPDATES_DB="/tmp/updates-db-${UID}/"
 
-if [[ -z $CHECKUPDATES_DB ]]; then
-	CHECKUPDATES_DB="${TMPDIR:-/tmp}/checkup-db-${UID}/"
-fi
+function create_db(){
+	local db="/var/lib/pacman/"
 
-trap 'rm -f $CHECKUPDATES_DB/db.lck' INT TERM EXIT
+	if [[ ! -d "$CHECKUPDATES_DB" ]]; then
+		mkdir -p "$CHECKUPDATES_DB"
+		ln -s "${db}/local" "$CHECKUPDATES_DB" &> /dev/null
+	fi
 
-DBPath="$(pacman-conf DBPath)"
-if [[ -z "$DBPath" ]] || [[ ! -d "$DBPath" ]]; then
-	DBPath="/var/lib/pacman/"
-fi
-
-mapfile -t updates < <(pacman -Qu --dbpath "$CHECKUPDATES_DB" 2> /dev/null | grep -v '\[.*\]')
+}
 
 function sync_db(){
-	mkdir -p "$CHECKUPDATES_DB"
-	ln -s "${DBPath}/local" "$CHECKUPDATES_DB" &> /dev/null
 	if ! fakeroot -- pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/null; then
-	    echo "error: Cannot fetch updates"
+		echo "error: Cannot fetch updates with pacman"
+		exit 1
+	elif ! paru -Say --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/null; then
+		echo "error: Cannot fetch updates with paru"
 		exit 1
 	fi
 }
 
 function notify_dunst(){
-	if [[ -x "$(command -v notify-send)" && "${#updates[@]}" > 0 ]]; then
-		notify-send "Update Available" "$(printf '%s\n' "${updates[@]}")"
+	local updates="$(pacman -Qu --dbpath $CHECKUPDATES_DB)"
+	local count="$(pacman -Qu --dbpath $CHECKUPDATES_DB | wc -l)"
+	if [[ $count > 0 ]]; then
+		dunstify "Update(s)" "$updates" -a "update" -r 755
+		echo $count "Updates(s)"
 	fi
+
 }
 
-if [[ -z "$1" ]]; then
-	sleep 10
+function check_connection(){
+	while ! nmcli g | awk '{ print $2 }' | grep comp &> /dev/null; do
+		sleep 10
+	done
+}
+
+function check_update(){
+	check_connection
+	create_db
 	sync_db
-	printf '%s %s' "${#updates[@]}" "Update(s)"
 	notify_dunst
-fi
+}
 
-if [[ "$1" == notify ]]; then
-	notify_dunst
-fi
-
+check_update
